version: 2
jobs:
  build:
      working_directory: ~/mern-starter
      docker:
        - image: circleci/node:10.16.3
      steps:
        - checkout
        - run:
            name: Install npm wee
            command: npm install
        - save_cache:
            key: dependency-cache-{{ checksum "package-lock.json" }}
            paths:
              - node_modules
  deploy: 
    docker: 
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $SERVER_USER@$SERVER_IP "./deploy-project.sh"
  
workflows:
  version: 2
  build_and_deploy:
      jobs:
        - build
        - deploy:
            filters:
              branches:
                only: master
            requires:
              - build
